### ISSUE TITLE
How to position the Speeddial button?

### ISSUE THREAD

**Issue by nponiros** [jampy/react-mui-speeddial#1]
In the developer console I managed to position the button by changing the styles of the container but from what I can see there is no support for changing the styles of the container without changing the react-mui-speeddial code. Is there any way to do what I want currently? If not I can open a PR to add support for a style attribute to style the container if you are interested.

**Comment by jampy** [comment]
You can do that with `style` now. Published as 0.0.6

**Comment by nponiros** [comment]
Okay, thanks
